= Movies Management And Tracking System (MMTS)

:spring_boot_version: 2.0.5.RELEASE
:spring-boot: https://github.com/spring-projects/spring-boot
:toc:
:icons: font
:source-highlighter: prettify

This projects helps demonstrate `clean, flexible, and maintainable code` by leveraging the programming constructs
from `Java,SpringBoot` applications as described in post here .


== What you need!
----
Java 11
SpringBoot 2.x
Embedded H2
Postgres
maven
----

== What you'll build
........
You'll build a Java, SpringBoot application with minimal microservices dependencies
demonstrating the following:

1. Clean User Request Validation +
2. Decouple exception handling code form business logic +
3. Vertical slicing to develop decomposable monolith +
4. Single Table design approach +
5. Developing event driven components using ApplicationEvent +
........

== Dependencies
........
Please check pom.xml for a list of all dependencies for other functionalities : 
Embedded H2, Postgres.
........

== Create Application
Here you create an `com.sdbawa.mmts.MoviesManagementAndTrackingApplication` Application:

== Application Domain
........
The domain code can be found in  src/main/java/com/sdbawa/mmts/domain/*

The code for higher order domain actors are vertically sliced. exp. movie, actor.

One vertical slice contains the end to end code with an idea no two domains share code.
........

== Common code

........
Shared concerns of the application located in

/com/sdbawa/mmts/common/*
/com/sdbawa/mmts/domain/events/*
/com/sdbawa/mmts/domain/statuslookup/*
........


=== Lookups
`com.sdbawa.mmts.domain.statuslookup` manages and provides status lookups all domains.

=== Application Events
ApplicationEvents used across application can be found in `com.sdbawa.mmts.domain.events.*` +

----
LoadStatusLookUpOnBootstrap.java is responsible to serve lookups from in-memory to
all modules in application.
Also, this class is responsible to load all lookups in-memory during bootstrap.
----

== Config
Application Configurations can be found in `com.sdbawa.mmts.config.*`

== DB schema
----
In memory H2 schema is located at src/main/resources/schema.sql
In memory H2 data is located at src/main/resources/data.sql
----

== Web Layer Tests
`src.test.com.sdbawa.mmts.controller.*` provides web layer tests for the RESTful APIs

== Running the application
To run the application, using Maven, execute:

[subs="attributes"]
----
mvn package && java -jar target/mmts-0.0.1-SNAPSHOT.jar
----

You will notice the output like this for a successful start of application:

........
2020-10-22 13:37:40.148  INFO 30880 --- [main] m.MoviesManagementAndTrackingApplication : Started MoviesManagementAndTrackingApplication in 6.297 seconds (JVM running for 8.511)
2020-10-22 13:37:40.988  INFO 30880 --- [-10.105.254.188] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-10-22 13:37:40.989  INFO 30880 --- [-10.105.254.188] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-10-22 13:37:41.002  INFO 30880 --- [-10.105.254.188] o.s.web.servlet.DispatcherServlet        : Completed initialization in 13 ms
........

== Port
Application is running at port 8080.


== In memory H2 database and app data
........
Check out data in-memory H2 database. http://localhost:8080/h2-console/

SELECT * FROM MOVIE
The result should show records.

This validates application is working fine.
........

== Spring ApplicationEvent
........
ApplicationEvents can be found in com.sdbawa.mmts.domain.events.*

select * from MOVIE_BUDGET_EVENTS - This should have NO records

........

== APIs
........
Add Endorsement

http://localhost:8080/endorsement/add +

Request: +
{ +
	"endorsementId" : 122, +
	"amount" : 500000, +
	"movieId" : 1 +
} +

Response : +
{ +
    "message": "success" +
} +

........

........
Update Actor status to confirm signing contract

http://localhost:8080/actor/status +

Request: +
{ +
	"actorId" : 1, +
	"statusId": 6, +
	"amount" : 100000, +
	"movieId" : 1 +
} +

Response: +
{ +
    "message": "success" +
} +
........

== Verification
........
 check database : select * from MOVIE_BUDGET_EVENTS +

 There should be 2 records with each event
........



