INSERT INTO STATUS_LOOKUP VALUES (1, 'ON_HOLD', 'MOVIE');
INSERT INTO STATUS_LOOKUP VALUES (2, 'UNDER_PRODUCTION', 'MOVIE');
INSERT INTO STATUS_LOOKUP VALUES (3, 'POST_PRODUCTION', 'MOVIE');
INSERT INTO STATUS_LOOKUP VALUES (4, 'RELEASED', 'MOVIE');
INSERT INTO STATUS_LOOKUP VALUES (5, 'CONTRACT_SENT', 'ACTOR');
INSERT INTO STATUS_LOOKUP VALUES (6, 'CONTRACT_SIGNED', 'ACTOR');
INSERT INTO STATUS_LOOKUP VALUES (7, 'CONTRACT_ACTIVE', 'ACTOR');
INSERT INTO STATUS_LOOKUP VALUES (8, 'RESTRICTED', 'ACTOR');
INSERT INTO STATUS_LOOKUP VALUES (9, 'CONTRACT_ACTIVE', 'DIRECTOR');
INSERT INTO STATUS_LOOKUP VALUES (10, 'CONTRACT_RELEASED', 'DIRECTOR');
INSERT INTO STATUS_LOOKUP VALUES (11, 'MALE', 'GENDER');
INSERT INTO STATUS_LOOKUP VALUES (12, 'FEMALE', 'GENDER');
INSERT INTO STATUS_LOOKUP VALUES (13, 'PREFER_NOT_TO_DISCLOSE', 'GENDER');
INSERT INTO STATUS_LOOKUP VALUES (14, 'NEUTRAL', 'GENDER');

INSERT INTO MOVIE(id, title, year, status_id, total_budget) VALUES (1, 'There we deal, together!', 2021, 1, 12100000);
INSERT INTO MOVIE(id, title, year, status_id, total_budget) VALUES (2, 'Summer of 2020', 2022, 3, 22965000);

INSERT INTO ACTOR(id, first_name, last_name, gender_id, status_id) VALUES (1, 'David', 'Mathewman', 11, 5);
INSERT INTO ACTOR(id, first_name, last_name, gender_id, status_id, amount) VALUES (2, 'Jonathan', 'Nef', 11, 7, 1250000);
INSERT INTO ACTOR(id, first_name, last_name, gender_id, status_id, amount) VALUES (3, 'Anne', 'Thomas', 13, 7, 2250000);

INSERT INTO DIRECTOR(id, first_name, last_name, gender_id, status_id) VALUES (1, 'Alice ', 'Smithers', 12, 9);
INSERT INTO DIRECTOR(id, first_name, last_name, gender_id, status_id) VALUES (2, 'Bobby', 'Jonas', 14, 10);
